import 'dart:math';
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';
import '../../app/theme/eazy_theme.dart';
import '../../core/network/api_client.dart';
import '../../core/network/api_exception.dart';
import '../home/home_shell.dart';

class WalletPage extends StatefulWidget{const WalletPage({super.key});@override State<WalletPage> createState()=>_WalletPageState();}
class _WalletPageState extends State<WalletPage>{
 final api=ApiClient();bool loading=true,busy=false;String? error;Map<String,dynamic> wallet={};List<Map<String,dynamic>> transactions=[];
 @override void initState(){super.initState();load();}
 Future<void> load()async{setState(()=>loading=true);try{final r=await Future.wait([api.get('wallet',auth:true),api.get('wallet/transactions?page=1&limit=20',auth:true)]);final w=r[0],t=r[1];final rw=w['wallets']??w['items']??w['wallet']??{};wallet=rw is List&&rw.isNotEmpty?Map<String,dynamic>.from(rw.first as Map):rw is Map?Map<String,dynamic>.from(rw):{};final rt=t['items']??t['transactions']??const[];transactions=(rt as List<dynamic>).map((e)=>Map<String,dynamic>.from(e as Map)).toList();error=null;}on ApiException catch(e){error=e.message;}finally{if(mounted)setState(()=>loading=false);}}
 String key(){return DateTime.now().microsecondsSinceEpoch.toString()+'-'+Random.secure().nextInt(1<<32).toString();}
 Future<void> deposit()async{final c=TextEditingController();final amount=await showDialog<String>(context:context,builder:(ctx)=>AlertDialog(title:const Text('Add money'),content:TextField(controller:c,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Amount',prefixText:'₦ ',hintText:'1000.00')),actions:[TextButton(onPressed:()=>Navigator.pop(ctx),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(ctx,c.text.trim()),child:const Text('Continue'))]));if(amount==null||!RegExp(r'^\\d+\\.\\d{2}$').hasMatch(amount))return;setState(()=>busy=true);try{final j=await api.post('payments/initialize',auth:true,body:{'purpose':'wallet_deposit','amount':amount,'currency':'NGN'},headers:{'Idempotency-Key':key()});final data=j['data'] is Map?Map<String,dynamic>.from(j['data'] as Map):j;final url=data['authorizationUrl']?.toString();if(url==null||!await launchUrl(Uri.parse(url),mode:LaunchMode.externalApplication))throw const ApiException('Payment provider did not return a checkout link.',kind:ApiErrorKind.provider);}on ApiException catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.message)));}finally{if(mounted)setState(()=>busy=false);}}
 Future<void> transfer()async{final u=TextEditingController(),a=TextEditingController();final data=await showDialog<Map<String,String>>(context:context,builder:(ctx)=>AlertDialog(title:const Text('Send money'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:u,decoration:const InputDecoration(labelText:'Recipient username',prefixText:'@ ')),const SizedBox(height:12),TextField(controller:a,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Amount',prefixText:'₦ '))]),actions:[TextButton(onPressed:()=>Navigator.pop(ctx),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(ctx,{'username':u.text.trim(),'amount':a.text.trim()}),child:const Text('Send'))]));if(data==null)return;final username=data['username']??'';final amount=data['amount']??'';if(!RegExp(r'^[a-zA-Z0-9_]{3,32}$').hasMatch(username)||!RegExp(r'^\\d+\\.\\d{2}$').hasMatch(amount))return;setState(()=>busy=true);try{await api.post('wallet/transfers',auth:true,body:{'recipientUsername':username.toLowerCase(),'amount':amount,'currency':'NGN'});if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Transfer submitted.')));await load();}on ApiException catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.message)));}finally{if(mounted)setState(()=>busy=false);}}
 @override Widget build(BuildContext context){return SafeArea(child:RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.only(bottom:32),children:[EazyPageHeader(title:'Wallet',subtitle:'Your money, clearly organised',trailing:IconButton(onPressed:load,icon:const Icon(Icons.refresh_rounded))),Padding(padding:const EdgeInsets.symmetric(horizontal:20),child:_Balance(wallet:wallet,loading:loading)),const SizedBox(height:16),Padding(padding:const EdgeInsets.symmetric(horizontal:20),child:Row(children:[Expanded(child:_Action(icon:Icons.arrow_upward_rounded,label:'Send',onTap:busy?null:transfer)),const SizedBox(width:10),Expanded(child:_Action(icon:Icons.add_rounded,label:'Add money',onTap:busy?null:deposit)),const SizedBox(width:10),Expanded(child:_Action(icon:Icons.receipt_long_rounded,label:'Refresh',onTap:busy?null:load))])),if(error!=null)Padding(padding:const EdgeInsets.all(20),child:Text(error!,style:const TextStyle(color:EazyColors.red))),const SizedBox(height:24),Padding(padding:const EdgeInsets.symmetric(horizontal:20),child:Text('Recent activity',style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.w900))),const SizedBox(height:10),if(transactions.isEmpty)const Padding(padding:EdgeInsets.symmetric(horizontal:20),child:Card(child:Padding(padding:EdgeInsets.all(24),child:Text('No transactions to show yet.',style:TextStyle(color:EazyColors.muted)))))else ...transactions.map((x)=>Padding(padding:const EdgeInsets.symmetric(horizontal:20,vertical:4),child:Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.receipt_long_outlined)),title:Text(x['type']?.toString()??'Transaction',style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text(x['status']?.toString()??'',style:const TextStyle(color:EazyColors.muted)),trailing:Text(x['amount']?.toString()??'',style:const TextStyle(fontWeight:FontWeight.w900))))))])));}
}
class _Balance extends StatelessWidget{const _Balance({required this.wallet,required this.loading});final Map<String,dynamic> wallet;final bool loading;@override Widget build(BuildContext context){final minor=wallet['availableBalanceMinor'];final amount=minor is num?minor/100:(wallet['availableBalance']??0);return Container(padding:const EdgeInsets.all(22),decoration:BoxDecoration(borderRadius:BorderRadius.circular(EazyRadius.xl),gradient:const LinearGradient(begin:Alignment.topLeft,end:Alignment.bottomRight,colors:[EazyColors.greenDeep,Color(0xFF0B4D32)])),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Available balance',style:TextStyle(color:Colors.white70)),const SizedBox(height:10),Text(loading?'••••••':'₦'+(amount is num?amount.toStringAsFixed(2):amount.toString()),style:const TextStyle(fontSize:34,fontWeight:FontWeight.w900,color:Colors.white)),const SizedBox(height:18),Text(wallet['status']?.toString()??'Eazy Wallet',style:const TextStyle(color:Colors.white70))]));}}
class _Action extends StatelessWidget{const _Action({required this.icon,required this.label,required this.onTap});final IconData icon;final String label;final VoidCallback? onTap;@override Widget build(BuildContext context)=>Card(child:InkWell(onTap:onTap,child:Padding(padding:const EdgeInsets.symmetric(vertical:17),child:Column(children:[Icon(icon,color:EazyColors.green),const SizedBox(height:7),Text(label,style:const TextStyle(fontWeight:FontWeight.w700,fontSize:12))]))));}