import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import '../../app/theme/eazy_theme.dart';
import '../../core/network/api_client.dart';
import '../../core/network/api_exception.dart';
import '../home/home_shell.dart';
import 'product_detail_page.dart';

class MarketplacePage extends StatefulWidget{const MarketplacePage({super.key});@override State<MarketplacePage> createState()=>_MarketplacePageState();}
class _MarketplacePageState extends State<MarketplacePage>{
 final api=ApiClient();final search=TextEditingController();bool loading=true;String? error;String? categoryId;List<Map<String,dynamic>> products=[];List<Map<String,dynamic>> categories=[];
 @override void initState(){super.initState();load();}@override void dispose(){search.dispose();super.dispose();}
 Future<void> load()async{setState(()=>loading=true);try{var path='marketplace/products?status=active&limit=30';if(categoryId!=null)path+='&categoryId='+categoryId!;if(search.text.trim().length>=2)path+='&q='+Uri.encodeQueryComponent(search.text.trim());final r=await Future.wait([api.get(path),api.get('marketplace/categories')]);final p=r[0],c=r[1];final pi=p['items']??p['products']??const[];final ci=c['items']??c['categories']??const[];products=(pi as List<dynamic>).map((e)=>Map<String,dynamic>.from(e as Map)).toList();categories=(ci as List<dynamic>).map((e)=>Map<String,dynamic>.from(e as Map)).toList();error=null;}on ApiException catch(e){error=e.message;}finally{if(mounted)setState(()=>loading=false);}}
 @override Widget build(BuildContext context){return SafeArea(child:RefreshIndicator(onRefresh:load,child:CustomScrollView(slivers:[
  SliverToBoxAdapter(child:EazyPageHeader(title:'Marketplace',subtitle:'Discover things worth having',trailing:IconButton(onPressed:()=>context.push('/cart'),icon:const Icon(Icons.shopping_cart_outlined)))),
  SliverToBoxAdapter(child:Padding(padding:const EdgeInsets.fromLTRB(20,0,20,14),child:TextField(controller:search,onSubmitted:(_)=>load(),decoration:InputDecoration(prefixIcon:const Icon(Icons.search_rounded),hintText:'Search products',suffixIcon:IconButton(onPressed:load,icon:const Icon(Icons.arrow_forward_rounded)))))),
  if(categories.isNotEmpty)SliverToBoxAdapter(child:SizedBox(height:50,child:ListView.separated(scrollDirection:Axis.horizontal,padding:const EdgeInsets.symmetric(horizontal:20),itemCount:categories.length+1,separatorBuilder:(_,_)=>const SizedBox(width:8),itemBuilder:(c,i){if(i==0)return ChoiceChip(label:const Text('All'),selected:categoryId==null,onSelected:(_){setState(()=>categoryId=null);load();});final x=categories[i-1];final id=x['id']?.toString();return ChoiceChip(label:Text(x['name']?.toString()??'Category'),selected:categoryId==id,onSelected:(_){setState(()=>categoryId=id);load();});}))),
  const SliverToBoxAdapter(child:SizedBox(height:14)),
  if(loading)const SliverFillRemaining(hasScrollBody:false,child:Center(child:CircularProgressIndicator())),
  if(!loading&&error!=null)SliverFillRemaining(hasScrollBody:false,child:_State(error!,load)),
  if(!loading&&error==null&&products.isEmpty)const SliverFillRemaining(hasScrollBody:false,child:_State('No products match your search.',null)),
  if(!loading&&products.isNotEmpty)SliverPadding(padding:const EdgeInsets.fromLTRB(20,0,20,24),sliver:SliverGrid.builder(gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,crossAxisSpacing:12,mainAxisSpacing:12,childAspectRatio:.72),itemCount:products.length,itemBuilder:(c,i)=>_Product(product:products[i])))
 ])));}}
class _Product extends StatelessWidget{const _Product({required this.product});final Map<String,dynamic> product;@override Widget build(BuildContext context){final raw=product['priceAmount']??product['priceMinor'];final price=raw is num?raw/((product['priceMinor']!=null)?100:1):0;return Card(child:InkWell(onTap:()=>Navigator.of(context).push(MaterialPageRoute(builder:(_)=>ProductDetailPage(product:product))),child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(child:Container(decoration:BoxDecoration(color:EazyColors.surfaceRaised,borderRadius:BorderRadius.circular(16)),child:const Center(child:Icon(Icons.shopping_bag_outlined,size:42,color:EazyColors.green)))),const SizedBox(height:10),Text(product['name']?.toString()??'Product',maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(fontWeight:FontWeight.w800)),const SizedBox(height:4),Text((product['currency']?.toString()??'NGN')+' '+(price is num?price.toStringAsFixed(2):price.toString()),style:const TextStyle(color:EazyColors.green,fontWeight:FontWeight.w900))]))));}}
class _State extends StatelessWidget{const _State(this.text,this.action);final String text;final VoidCallback? action;@override Widget build(BuildContext context){return Center(child:Padding(padding:const EdgeInsets.all(28),child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.storefront_outlined,size:44,color:EazyColors.green),const SizedBox(height:12),Text(text,textAlign:TextAlign.center,style:const TextStyle(color:EazyColors.muted)),if(action!=null)...[const SizedBox(height:12),OutlinedButton(onPressed:action,child:const Text('Try again'))]])));}}