import 'package:flutter/material.dart';
import '../../app/theme/eazy_theme.dart';
import '../../core/network/api_client.dart';
import '../../core/network/api_exception.dart';
class NotificationsPage extends StatefulWidget{const NotificationsPage({super.key});@override State<NotificationsPage> createState()=>_NotificationsPageState();}
class _NotificationsPageState extends State<NotificationsPage>{final api=ApiClient();List<Map<String,dynamic>> items=[];int unread=0;String error='';bool loading=true;
@override void initState(){super.initState();load();}Future<void> load()async{try{final r=await api.get('notifications?page=1&limit=30',auth:true),c=await api.get('notifications/unread-count',auth:true);if(mounted)setState(()=>{items=(r['items'] as List? ?? []).whereType<Map>().map((e)=>Map<String,dynamic>.from(e)).toList(),unread=(c['unreadCount'] as num?)?.toInt()??0});}on ApiException catch(e){if(mounted)setState(()=>error=e.message);}finally{if(mounted)setState(()=>loading=false);}}
Future<void> read(String id)async{try{await api.post('notifications/$id/read',auth:true);await load();}catch(_){}}Future<void> readAll()async{try{await api.post('notifications/read-all',auth:true);await load();}catch(_){}}IconData icon(String? t)=>switch(t){'follow'=>Icons.person_add_alt_1_rounded,'like'=>Icons.favorite_rounded,'comment'=>Icons.mode_comment_rounded,_=>Icons.notifications_rounded};
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text(unread>0?'Notifications ($unread)':'Notifications',style:const TextStyle(fontWeight:FontWeight.w900)),actions:[TextButton(onPressed:unread==0?null:readAll,child:const Text('Read all'))]),body:RefreshIndicator(onRefresh:load,child:loading?const Center(child:CircularProgressIndicator()):error.isNotEmpty?ListView(children:[Padding(padding:const EdgeInsets.all(24),child:Text(error,style:const TextStyle(color:EazyColors.red))) ]):items.isEmpty?ListView(children:[const SizedBox(height:180),Center(child:Text('You’re all caught up.',style:TextStyle(color:EazyColors.muted))) ]):ListView.builder(padding:const EdgeInsets.all(12),itemCount:items.length,itemBuilder:(_,i){final n=items[i];return Card(child:ListTile(onTap:()=>read(n['id'].toString()),leading:CircleAvatar(child:Icon(icon(n['type']?.toString()))),title:Text(n['title']?.toString()??'Eazy notification'),subtitle:Text(n['body']?.toString()??'Activity on Eazy'),trailing:n['isRead']==true?null:const Icon(Icons.circle,size:9,color:EazyColors.green)));})));}}
