import 'package:flutter/material.dart';
import '../../app/theme/eazy_theme.dart';
import '../../core/network/api_client.dart';
import '../../core/network/api_exception.dart';
class SecurityPage extends StatefulWidget{const SecurityPage({super.key});@override State<SecurityPage> createState()=>_SecurityPageState();}
class _SecurityPageState extends State<SecurityPage>{final api=ApiClient();List<Map<String,dynamic>> sessions=[];bool loading=true;String error='';
@override void initState(){super.initState();load();}Future<void> load()async{try{final r=await api.get('auth/sessions',auth:true);final x=(r['sessions'] as List? ?? r['items'] as List? ?? []);if(mounted)setState(()=>sessions=x.whereType<Map>().map((e)=>Map<String,dynamic>.from(e)).toList());}on ApiException catch(e){if(mounted)setState(()=>error=e.message);}finally{if(mounted)setState(()=>loading=false);}}
Future<void> revoke(String id)async{try{await api.post('auth/sessions/$id/revoke',auth:true);await load();}on ApiException catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.message)));}}
Future<void> revokeAll()async{final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('Revoke all sessions?'),content:const Text('This signs out every Eazy application session, including this device.'),actions:[TextButton(onPressed:()=>Navigator.pop(context,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('Revoke all'))]));if(ok!=true)return;try{await api.post('auth/sessions/revoke-all',auth:true);await load();}catch(_){}} 
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Security & sessions',style:TextStyle(fontWeight:FontWeight.w900))),body:loading?const Center(child:CircularProgressIndicator()):RefreshIndicator(onRefresh:load,child:ListView(padding:const EdgeInsets.all(16),children:[const Card(child:Padding(padding:EdgeInsets.all(16),child:Text('Eazy sessions are server-side sessions bound to your verified Firebase identity. Revoking one blocks further API use from that session.',style:TextStyle(color:EazyColors.muted,height:1.35)))),if(error.isNotEmpty)Text(error,style:const TextStyle(color:EazyColors.red)),...sessions.map((s)=>Card(child:ListTile(leading:Icon(s['isCurrent']==true?Icons.phone_android_rounded:Icons.devices_other_rounded,color:EazyColors.green),title:Text(s['isCurrent']==true?'This device':'Eazy session'),subtitle:Text(s['status']?.toString()??'active'),trailing:s['isCurrent']==true?const Icon(Icons.verified_user_rounded):TextButton(onPressed:()=>revoke(s['id'].toString()),child:const Text('Revoke'))))),OutlinedButton.icon(onPressed:sessions.isEmpty?null:revokeAll,icon:const Icon(Icons.logout_rounded),label:const Text('Revoke all sessions'))])));}}
